# Generated by Django 3.1.4 on 2020-12-07 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(max_length=4),
        ),
    ]
