# Generated by Django 3.1.4 on 2020-12-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='album',
            name='year',
        ),
        migrations.RemoveField(
            model_name='book',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='book',
            name='year',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
        migrations.AddField(
            model_name='album',
            name='owner',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='movie',
            name='owner',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='album',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='album',
            name='label',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='book',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='movie',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='movie',
            name='studio',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
