# Generated by Django 3.1.4 on 2020-12-07 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0002_auto_20201206_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='album',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='book',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='book',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='date_added',
        ),
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.DateField(),
        ),
    ]
