# Generated by Django 3.1.4 on 2020-12-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0003_auto_20201207_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='album',
            name='label',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='album',
            name='year',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='movie',
            name='studio',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.DateField(blank=True),
        ),
    ]
