# Generated by Django 3.1.4 on 2020-12-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0004_auto_20201207_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='owner',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
