# Generated by Django 3.1.4 on 2020-12-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0005_movie_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='owner',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
