# Generated by Django 3.1.4 on 2020-12-08 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0006_auto_20201207_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='book',
            name='year',
        ),
    ]
