# Generated by Django 3.1.4 on 2020-12-08 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0007_auto_20201207_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='year',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
        migrations.AddField(
            model_name='book',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='book',
            name='owner',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
