# Generated by Django 3.1.4 on 2020-12-08 19:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('curator', '0010_auto_20201208_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='owner',
        ),
        migrations.AddField(
            model_name='movie',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
