# Generated by Django 3.1.4 on 2020-12-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0012_auto_20201208_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='user',
        ),
        migrations.AddField(
            model_name='movie',
            name='owner',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
