# Generated by Django 3.1.4 on 2020-12-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curator', '0013_auto_20201208_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='owner',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
